[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reaper_api_usage"
version = "0.1.0"
description = "REAPER DAW integration using MCP"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "python-reapy>=0.9.0",
    "python-osc>=1.8.0",
    "pytest>=7.0.0",
    "mcp[cli]>=0.1.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
]

[project.urls]
Homepage = "https://github.com/yourusername/reaper_api_usage"
Repository = "https://github.com/yourusername/reaper_api_usage.git"
Issues = "https://github.com/yourusername/reaper_api_usage/issues"

[tool.setuptools]
packages = ["src"] 