"""Constants for REAPER MCP project."""

# Network/Connection Constants
REAPER_DEFAULT_PORTS = [2306, 2307, 2308, 2309]

# Audio Constants
DB_CONVERSION_FACTOR = 20.0
SILENCE_THRESHOLD_DB = -150.0
MINIMUM_PEAK_VALUE = 1e-30

# MIDI Constants
MIDI_MAX_VALUE = 127
MIDI_DEFAULT_VELOCITY = 96
MIDI_MIDDLE_C = 60

# Track Constants
DEFAULT_STEREO_CHANNELS = 2
DB_VOLUME_CONVERSION_FACTOR = 10.0

# Automation Constants
AUTOMATION_MODE_TRIM = 2
AUTOMATION_MODE_TOUCH = 3
AUTOMATION_MODE_LATCH = 4

# Project Constants
TEMPO_DECIMAL_PLACES = 3

# Time Conversion Constants
SECONDS_PER_MINUTE = 60.0
POSITION_COMPONENTS_COUNT = 2
